server:
  port: 8082

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://popitdb.cljjw1huggky.ap-northeast-2.rds.amazonaws.com:3306/popit_set_DB
    username: popitAdmin
    password: popit123
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
google:
  client:
    id: ${GOOGLE_ID}
    pw: ${GOOGLE_PW}

cloud:
  aws:
    s3:
      bucket: popits3
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB